openapi: 3.0.1
info:
  version: 1.0.0
  title: Tuiter
  description: ""

servers:
  - url: http://localhost:3000

paths:
  "/posts":
    get:
      summary: List all posts
      operationId: getAllPost
      responses:
        '200':
          description: 'Show All'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '422':
          description: 'Error: Unprocessable'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422Result'
              examples:
                errorExample:
                  $ref: '#/components/examples/error422'


      security:
        - API-KEY: []
  "/posts/{postId}":
    parameters:
      - name: postId
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: Show post
      operationId: getPost
      responses:
        '200':
          description: 'Show'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
    put:
      summary: Update post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '200':
          description: 'Updated'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '403':
          description: 'Error: Unauthorised'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error403'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []
    delete:
      summary: Delete post
      responses:
        '200':
          description: 'Deleted'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Post was successfully destroyed.'
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '403':
          description: 'Error: Unauthorised'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error403'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []
  "/posts/{postId}/like":
    parameters:
      - name: postId
        in: path
        description: id
        required: true
        schema:
          type: string
    put:
      summary: Like post
      responses:
        '200':
          description: 'Liked'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You've liked this post."
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []
  "/posts/{postId}/dislike":
    parameters:
      - name: postId
        in: path
        description: id
        required: true
        schema:
          type: string
    put:
      summary: Dislike post
      responses:
        '200':
          description: 'Disliked'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You've disiked this post."
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []
  "/posts/{postId}/boost":
    parameters:
      - name: postId
        in: path
        description: Boost Post
        required: true
        schema:
          type: string
    put:
      summary: Boost post
      responses:
        '200':
          description: 'Boosted'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You've boosted this post."
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []

  "/posts/{postId}/comments":
    parameters:
      - name: postId
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: List comments for a post
      operationId: getPostComments
      responses:
        '200':
          description: 'Show'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
    post:
      summary: Add a comment to a post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '422':
          description: 'Error: Unprocessable'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422Result'
              examples:
                errorExample:
                  $ref: '#/components/examples/error422'
      security:
        - API-KEY: []

  "/posts/{postId}/comments/{commentId}":
    parameters:
      - name: postId
        in: path
        description: ID of the post
        required: true
        schema:
          type: string
      - name: commentId
        in: path
        description: ID of the comment
        required: true
        schema:
          type: string
    delete:
      summary: Delete a comment from a post
      responses:
        '200':
          description: 'Deleted'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Comment was successfully destroyed.'
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '403':
          description: 'Error: Unauthorised'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error403'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []
    put:
      summary: Update comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        '200':
          description: 'Updated'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '403':
          description: 'Error: Unauthorised'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error403'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: []

  "/posts/{postId}/comments/{commentId}/like":
    parameters:
      - name: postId
        in: path
        description: ID of the post
        required: true
        schema:
          type: string
      - name: commentId
        in: path
        description: ID of the comment
        required: true
        schema:
          type: string
    put:
      summary: Like comment
      responses:
        '200':
          description: 'Liked'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You've liked this comment."
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: [ ]

  "/posts/{postId}/comments/{commentId}/dislike":
    parameters:
      - name: postId
        in: path
        description: ID of the post
        required: true
        schema:
          type: string
      - name: commentId
        in: path
        description: ID of the comment
        required: true
        schema:
          type: string
    put:
      summary: Dislike comment
      responses:
        '200':
          description: 'Disliked'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "You've disiked this comment."
        '401':
          description: 'Error: Forbidden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
        '404':
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'
      security:
        - API-KEY: [ ]


components:
  securitySchemes:
    API-KEY:
      type: apiKey
      name: API-KEY
      in: header

  schemas:
    NewPost:
      type: object
      properties:
        title:
          type: string
          example: 'post title'
        body:
          type: string
          example: 'post body'
        magazine_id:
          type: integer
          format: int64
          example: 1
        url:
          type: string
          example: 'google.com'

    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        title:
          type: string
          minLength: 4
          example: 'My name'
        body:
          type: string
          minLength: 4
          maxLength: 280
          example: 'My content'
        url:
          type: string
          format: url
          example: google.com
        created_at:
          type: string
          format: date-time
        comments_count:
          type: integer
          format: int64
          example: 0
        likes_count:
          type: integer
          format: int64
          example: 0
        dislikes_count:
          type: integer
          format: int64
          example: 0
        boosts_count:
          type: integer
          format: int64
          example: 0
        user_name:
          type: string
          example: author
        magazine_name:
          type: string
          example: magazine

    ErrorResult:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    Error422Result:
      type: object
      additionalProperties:
        type: array
        items:
          type: string

    NewComment:
      type: object
      properties:
        body:
          type: string
          example: 'This is a comment'
        comment_id:
          type: integer
          format: int64
          example: 1
          description: 'Optional. If present, this comment is a reply to the comment with this ID.'

    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        body:
          type: string
          example: 'This is a comment'
        createdAt:
          type: string
          format: date-time
        user_name:
          type: string
          example: author
        post_title:
          type: string
          example: post
        replies_count:
          type: integer
          format: int64
          example: 0
        likes_count:
          type: integer
          format: int64
          example: 0
        dislikes_count:
          type: integer
          format: int64
          example: 0

  examples:
    error404:
      value:
        message: "Record not found"
    error403:
      value:
        message: "You are not authorized to perform this action."
    error401:
      value:
        message: "Invalid API-KEY"
    error422:
      value:
        title: ["can't be blank"]
        magazine: ["must exist"]
        